### ISSUE TITLE
errors on nic deletion on vm

### ISSUE THREAD

**Issue by gregorybrzeski** [hyperonecom/h1-cli#413]
```
$ h1 vm nic delete --vm 5d7533a3d39c328440cea7ff --nic 5d7533a4d39c328440cea7ff
? Are you sure you want to delete resource "5d7533a4d39c328440cea7ff"?: Yes
error: Uncaught error: TypeError: join() expected argument 2 to be type 9 but received type 7 instead.
error: Error: TypeError: join() expected argument 2 to be type 9 but received type 7 instead.
    at Runtime._validateArgs (/snapshot/h1-cli/node_modules/jmespath/jmespath.js:1252:23)
    at Runtime.callFunction (/snapshot/h1-cli/node_modules/jmespath/jmespath.js:1214:12)
    at TreeInterpreter.visit (/snapshot/h1-cli/node_modules/jmespath/jmespath.js:1068:35)
    at TreeInterpreter.visit (/snapshot/h1-cli/node_modules/jmespath/jmespath.js:1037:46)
    at TreeInterpreter.visit (/snapshot/h1-cli/node_modules/jmespath/jmespath.js:936:32)
    at TreeInterpreter.search (/snapshot/h1-cli/node_modules/jmespath/jmespath.js:862:23)
    at Object.search (/snapshot/h1-cli/node_modules/jmespath/jmespath.js:1660:26)
    at queryFilter (/snapshot/h1-cli/bin/_plugins/outputFormat/index.js:13:23)
    at Object.table (/snapshot/h1-cli/bin/_plugins/outputFormat/index.js:19:18)
    at Object.sendOutput (/snapshot/h1-cli/bin/_plugins/outputFormat/index.js:76:86)
    at Namespace.handler [as $handler] (/snapshot/h1-cli/bin/generic/delete/index.js:36:33)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

h1-cli version 1.7.0

**Comment by ad-m** [comment]
@fredericosilva , public API inconsistently responds.

* ```POST /vm/xxx/netadp``` returns vm 
* ```GET /vm/xxx/netadp``` returns array of netadp
* ```DELETE /vm/xxx/netadp``` returns vm

```
$ h1 vm nic create --network my-network --vm vm-windows --type public -o json -v
verbose: body
{
  "type": "public",
  "tag": {},
  "network": "my-network"
}
verbose: POST https://api.hyperone.com/v1/vm/vm-windows/netadp
verbose: headers
{
...
}
verbose: status
200
verbose: headers
{
  "server": "nginx",
  "date": "Sun, 08 Sep 2019 20:31:56 GMT",
  "content-type": "application/json; charset=utf-8",
  "transfer-encoding": "chunked",
  "connection": "close",
  "vary": "Accept-Encoding",
...
  "x-event-id": "5d756535d39c328440cecd8d",
  "etag": "W/\"486-Z9ZJhXKjQpRz5aqW//R17uMJXZk\"",
  "x-xss-protection": "1; mode=block",
  "x-frame-options": "DENY",
  "x-content-type-options": "nosniff",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "referrer-policy": "strict-origin-when-cross-origin",
  "content-encoding": "gzip"
}
{
  _id: '5d756536d39c328440cecd8e',
  id: '5d756536d39c328440cecd8e',
  name: '00155DFFD9A1',
  services: [
    {
      _id: '5d756536e2d9af262cd6da50',
      type: 'flavour',
      name: 'public',
      data: { type: 'public', speed: 1000 },
      billing: '5d756536e2d9af262cd6da4f',
      sourceService: '561e7e30a8cfd461e469ad18'
    },
    {
      _id: '5d756536e2d9af262cd6da52',
      type: 'metric',
      name: 'metric traffic Outbound',
      data: { metric: 'rbx.vm.*.netadp.%s.traffic.Outgoing' },
      billing: '5d756536e2d9af262cd6da51',
      sourceService: '57a88f8a9ce9da3f72e30fdc'
    }
  ],
  flavour: 'public',
  modifiedOn: '2019-09-08T20:31:50.026Z',
  modifiedBy: 'a.dobrawy@hyperone.com',
  createdBy: 'a.dobrawy@hyperone.com',
  createdOn: '2019-09-08T20:31:50.022Z',
  accessRights: [ '5af0bbbcb7802508ad844caa' ],
  processing: false,
  created: true,
  queue: [
    {
      _id: '5d756536d39c328440cecd8f',
      name: 'create',
      createdBy: 'a.dobrawy@hyperone.com',
      queued: '2019-09-08T20:31:50.026Z',
      state: 'finished',
      resource: { id: '5d756536d39c328440cecd8e', type: 'netadp' }
    }
  ],
  state: 'Unknown',
  tag: {},
  billingTenant: '5af0bbbcb7802508ad844caa',
  project: '5af0bbbcb7802508ad844caa',
  fqdn: '5d756536d39c328440cecd8e.netadp.pl-waw-1.hyperone.cloud',
  memory: null
}
$ h1 vm nic list --vm vm-windows -o json
verbose: GET https://api.hyperone.com/v1/vm/vm-windows/netadp
verbose: headers
{
...
}
verbose: query {}
verbose: 200 OK

[
  {
    _id: '5d0c39370136a7f0da4e4972',
    id: '5d0c39370136a7f0da4e4972',
    name: '00155DFFDDA7',
    services: [
      {
        type: 'flavour',
        name: 'private',
        data: { speed: 1000, type: 'private' },
        billing: '5d0c3937b79f0f7553877119',
        sourceService: '570a3f8f9ce9da3f72e30fce',
        _id: '5d0c3937b79f0f755387711a'
      }
    ],
    flavour: 'private',
    modifiedOn: '2019-06-21T06:08:47.723Z',
    modifiedBy: 'karol.bregula@siecobywatelska.pl',
    createdBy: 'karol.bregula@siecobywatelska.pl',
    createdOn: '2019-06-21T01:56:07.075Z',
    accessRights: [ '5af0bbbcb7802508ad844caa' ],
    processing: false,
    created: true,
    queue: [
      {
        _id: '5d0c39370136a7f0da4e4973',
        name: 'create',
        createdBy: 'karol.bregula@siecobywatelska.pl',
        queued: '2019-06-21T01:56:07.079Z',
        state: 'finished',
        resource: { id: '5d0c39370136a7f0da4e4972', type: 'netadp' }
      }
    ],
    state: 'Online',
    tag: {},
    billingTenant: '5af0bbbcb7802508ad844caa',
    project: '5af0bbbcb7802508ad844caa',
    macaddress: '00:15:5D:FF:DD:A7',
    speed: 1000,
    fqdn: '5d0c39370136a7f0da4e4972.netadp.pl-waw-1.hyperone.cloud',
    network: {
      _id: '5bbf6f543e43d372f17e9a1f',
      id: '5bbf6f543e43d372f17e9a1f',
      name: 'network-windows',
      flavour: 'custom',
      modifiedOn: '2019-07-03T10:00:14.176Z',
      modifiedBy: 'karol.bregula@siecobywatelska.pl',
      createdBy: 'karol.bregula@siecobywatelska.pl',
      createdOn: '2018-10-11T15:42:12.041Z',
      accessRights: [ '5af0bbbcb7802508ad844caa' ],
      processing: false,
      created: true,
      queue: [
        {
          _id: '5bbf6f543e43d372f17e9a20',
          name: 'create',
          createdBy: 'karol.bregula@siecobywatelska.pl',
          queued: '2018-10-11T15:42:12.044Z',
          state: 'finished',
          resource: { id: '5bbf6f543e43d372f17e9a1f', type: 'network' }
        }
      ],
      state: 'Online',
      tag: {},
      billingTenant: '5af0bbbcb7802508ad844caa',
      project: '5af0bbbcb7802508ad844caa',
      address: '10.182.99.0/24',
      gateway: '10.182.99.1',
      type: 'private',
      dns: { nameservers: [ '9.9.9.9', '8.8.8.8' ] },
      netgw: '5bbf7382ede9d5980ef209be'
    },
    ip: [
      {
        _id: '5bbf735658cb2c02ada53223',
        id: '5bbf735658cb2c02ada53223',
        name: '10.182.99.11',
        flavour: 'custom',
        modifiedOn: '2018-10-11T15:59:18.996Z',
        modifiedBy: '',
        createdBy: '',
        createdOn: '2018-10-11T15:59:18.996Z',
        accessRights: [ '5af0bbbcb7802508ad844caa' ],
        processing: false,
        created: true,
        queue: [],
        state: 'Allocated',
        tag: {},
        project: '5af0bbbcb7802508ad844caa',
        address: '10.182.99.11',
        fqdn: '5bbf735658cb2c02ada53223.ip.pl-waw-1.hyperone.cloud',
        mac: '5d0c39370136a7f0da4e4972',
        network: '5bbf6f543e43d372f17e9a1f',
        ptrRecord: 'host-10-182-99-11',
        persistent: true,
        associated: { netadp: '5d0c39370136a7f0da4e4972' }
      },
      {
        _id: '5c9b993c3afea49e51bb481f',
        id: '5c9b993c3afea49e51bb481f',
        name: '10.182.99.27',
        flavour: 'custom',
        modifiedOn: '2019-03-27T15:39:40.605Z',
        modifiedBy: '',
        createdBy: '',
        createdOn: '2019-03-27T15:39:40.605Z',
        accessRights: [ '5af0bbbcb7802508ad844caa' ],
        processing: false,
        created: true,
        queue: [],
        state: 'Allocated',
        tag: {},
        project: '5af0bbbcb7802508ad844caa',
        address: '10.182.99.27',
        fqdn: '5c9b993c3afea49e51bb481f.ip.pl-waw-1.hyperone.cloud',
        mac: '5d0c39370136a7f0da4e4972',
        network: '5bbf6f543e43d372f17e9a1f',
        ptrRecord: 'host-10-182-99-27',
        persistent: true,
        associated: { netadp: '5d0c39370136a7f0da4e4972' }
      },
      {
        _id: '5c9ba8b4c3a31d5198108651',
        id: '5c9ba8b4c3a31d5198108651',
        name: '10.182.99.10',
        flavour: 'custom',
        modifiedOn: '2019-03-27T16:45:40.736Z',
        modifiedBy: 'karol.bregula@siecobywatelska.pl',
        createdBy: 'karol.bregula@siecobywatelska.pl',
        createdOn: '2019-03-27T16:45:40.736Z',
        accessRights: [ '5af0bbbcb7802508ad844caa' ],
        processing: false,
        created: true,
        queue: [],
        state: 'Allocated',
        tag: {},
        project: '5af0bbbcb7802508ad844caa',
        address: '10.182.99.10',
        fqdn: '5c9ba8b4c3a31d5198108651.ip.pl-waw-1.hyperone.cloud',
        mac: '5d0c39370136a7f0da4e4972',
        network: '5bbf6f543e43d372f17e9a1f',
        ptrRecord: 'host-10-182-99-10',
        persistent: true,
        associated: { netadp: '5d0c39370136a7f0da4e4972' }
      },
      {
        _id: '5c9ba8f1c3a31d5198108655',
        id: '5c9ba8f1c3a31d5198108655',
        name: '10.182.99.12',
        flavour: 'custom',
        modifiedOn: '2019-03-27T16:46:41.939Z',
        modifiedBy: 'karol.bregula@siecobywatelska.pl',
        createdBy: 'karol.bregula@siecobywatelska.pl',
        createdOn: '2019-03-27T16:46:41.939Z',
        accessRights: [ '5af0bbbcb7802508ad844caa' ],
        processing: false,
        created: true,
        queue: [],
        state: 'Allocated',
        tag: {},
        project: '5af0bbbcb7802508ad844caa',
        address: '10.182.99.12',
        fqdn: '5c9ba8f1c3a31d5198108655.ip.pl-waw-1.hyperone.cloud',
        mac: '5d0c39370136a7f0da4e4972',
        network: '5bbf6f543e43d372f17e9a1f',
        ptrRecord: 'host-10-182-99-12',
        persistent: true,
        associated: { netadp: '5d0c39370136a7f0da4e4972' }
      },
      {
        _id: '5c9baa2bc3a31d5198108681',
        id: '5c9baa2bc3a31d5198108681',
        name: '10.182.99.13',
        flavour: 'custom',
        modifiedOn: '2019-03-27T16:51:55.345Z',
        modifiedBy: 'karol.bregula@siecobywatelska.pl',
        createdBy: 'karol.bregula@siecobywatelska.pl',
        createdOn: '2019-03-27T16:51:55.345Z',
        accessRights: [ '5af0bbbcb7802508ad844caa' ],
        processing: false,
        created: true,
        queue: [],
        state: 'Allocated',
        tag: {},
        project: '5af0bbbcb7802508ad844caa',
        address: '10.182.99.13',
        fqdn: '5c9baa2bc3a31d5198108681.ip.pl-waw-1.hyperone.cloud',
        mac: '5d0c39370136a7f0da4e4972',
        network: '5bbf6f543e43d372f17e9a1f',
        ptrRecord: 'host-10-182-99-13',
        persistent: true,
        associated: { netadp: '5d0c39370136a7f0da4e4972' }
      },
      {
        _id: '5d0c3937b79f0f7553877117',
        id: '5d0c3937b79f0f7553877117',
        name: '10.182.99.32',
        flavour: 'custom',
        modifiedOn: '2019-06-21T01:56:07.241Z',
        modifiedBy: '',
        createdBy: '',
        createdOn: '2019-06-21T01:56:07.241Z',
        accessRights: [ '5af0bbbcb7802508ad844caa' ],
        processing: false,
        created: true,
        queue: [],
        state: 'Allocated',
        tag: {},
        project: '5af0bbbcb7802508ad844caa',
        address: '10.182.99.32',
        fqdn: '5d0c3937b79f0f7553877117.ip.pl-waw-1.hyperone.cloud',
        mac: '5d0c39370136a7f0da4e4972',
        network: '5bbf6f543e43d372f17e9a1f',
        ptrRecord: 'host-10-182-99-32',
        persistent: true,
        associated: { netadp: '5d0c39370136a7f0da4e4972' }
      }
    ],
    assigned: { resource: 'vm', id: '5b698289d242500e34ae43b6' },
    firewall: '5d0c26e80136a7f0da4e3fe0'
  },
  {
    _id: '5d756536d39c328440cecd8e',
    id: '5d756536d39c328440cecd8e',
    name: '00155DFFD9A1',
    services: [
      {
        _id: '5d756536e2d9af262cd6da50',
        type: 'flavour',
        name: 'public',
        data: { type: 'public', speed: 1000 },
        billing: '5d756536e2d9af262cd6da4f',
        sourceService: '561e7e30a8cfd461e469ad18'
      },
      {
        _id: '5d756536e2d9af262cd6da52',
        type: 'metric',
        name: 'metric traffic Outbound',
        data: { metric: 'rbx.vm.*.netadp.%s.traffic.Outgoing' },
        billing: '5d756536e2d9af262cd6da51',
        sourceService: '57a88f8a9ce9da3f72e30fdc'
      }
    ],
    flavour: 'public',
    modifiedOn: '2019-09-08T20:31:50.026Z',
    modifiedBy: 'a.dobrawy@hyperone.com',
    createdBy: 'a.dobrawy@hyperone.com',
    createdOn: '2019-09-08T20:31:50.022Z',
    accessRights: [ '5af0bbbcb7802508ad844caa' ],
    processing: false,
    created: true,
    queue: [
      {
        _id: '5d756536d39c328440cecd8f',
        name: 'create',
        createdBy: 'a.dobrawy@hyperone.com',
        queued: '2019-09-08T20:31:50.026Z',
        state: 'finished',
        resource: { id: '5d756536d39c328440cecd8e', type: 'netadp' }
      }
    ],
    state: 'Online',
    tag: {},
    billingTenant: '5af0bbbcb7802508ad844caa',
    project: '5af0bbbcb7802508ad844caa',
    macaddress: '00:15:5D:FF:D9:A1',
    speed: 1000,
    fqdn: '5d756536d39c328440cecd8e.netadp.pl-waw-1.hyperone.cloud',
    network: {
      _id: '5d756489d39c328440cecd57',
      id: '5d756489d39c328440cecd57',
      name: 'my-network',
      flavour: 'custom',
      modifiedOn: '2019-09-08T20:28:57.749Z',
      modifiedBy: 'a.dobrawy@hyperone.com',
      createdBy: 'a.dobrawy@hyperone.com',
      createdOn: '2019-09-08T20:28:57.747Z',
      accessRights: [ '5af0bbbcb7802508ad844caa' ],
      processing: false,
      created: true,
      queue: [
        {
          _id: '5d756489d39c328440cecd58',
          name: 'create',
          createdBy: 'a.dobrawy@hyperone.com',
          queued: '2019-09-08T20:28:57.749Z',
          state: 'finished',
          resource: { id: '5d756489d39c328440cecd57', type: 'network' }
        }
      ],
      state: 'Online',
      tag: {},
      project: '5af0bbbcb7802508ad844caa',
      address: '10.144.29.0/24',
      gateway: '10.144.29.1',
      type: 'private',
      dns: { nameservers: [ '9.9.9.9', '8.8.8.8' ] }
    },
    ip: [
      {
        _id: '5d756536e2d9af262cd6da4c',
        id: '5d756536e2d9af262cd6da4c',
        name: '10.144.29.12',
        flavour: 'custom',
        modifiedOn: '2019-09-08T20:31:50.249Z',
        modifiedBy: '',
        createdBy: '',
        createdOn: '2019-09-08T20:31:50.249Z',
        accessRights: [ '5af0bbbcb7802508ad844caa' ],
        processing: false,
        created: true,
        queue: [],
        state: 'Allocated',
        tag: {},
        project: '5af0bbbcb7802508ad844caa',
        address: '10.144.29.12',
        fqdn: '5d756536e2d9af262cd6da4c.ip.pl-waw-1.hyperone.cloud',
        mac: '5d756536d39c328440cecd8e',
        network: '5d756489d39c328440cecd57',
        ptrRecord: 'host-10-144-29-12',
        persistent: true,
        associated: { netadp: '5d756536d39c328440cecd8e' }
      }
    ],
    assigned: { resource: 'vm', id: '5b698289d242500e34ae43b6' }
  }
]
$ h1 vm nic delete --vm vm-windows --nic 5d756536d39c328440cecd8e -v -o json
? Are you sure you want to delete resource "5d756536d39c328440cecd8e"?: Yes
verbose: body
{}
verbose: DELETE https://api.hyperone.com/v1/vm/vm-windows/netadp/5d756536d39c328440cecd8e
verbose: headers
{
...
}
verbose: status
200
verbose: headers
{
  "server": "nginx",
  "date": "Sun, 08 Sep 2019 20:38:44 GMT",
  "content-type": "application/json; charset=utf-8",
  "transfer-encoding": "chunked",
  "connection": "close",
  "vary": "Accept-Encoding",
...
  "x-event-id": "5d7566ced39c328440cecd93",
  "etag": "W/\"551-VyEfd5fl7rvyAiuZA3qs55r7pvc\"",
  "x-xss-protection": "1; mode=block",
  "x-frame-options": "DENY",
  "x-content-type-options": "nosniff",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "referrer-policy": "strict-origin-when-cross-origin",
  "content-encoding": "gzip"
}
{
  _id: '5d756536d39c328440cecd8e',
  id: '5d756536d39c328440cecd8e',
  name: '00155DFFD9A1',
  services: [
    {
      _id: '5d756536e2d9af262cd6da50',
      type: 'flavour',
      name: 'public',
      data: { type: 'public', speed: 1000 },
      billing: '5d756536e2d9af262cd6da4f',
      sourceService: '561e7e30a8cfd461e469ad18'
    },
    {
      _id: '5d756536e2d9af262cd6da52',
      type: 'metric',
      name: 'metric traffic Outbound',
      data: { metric: 'rbx.vm.*.netadp.%s.traffic.Outgoing' },
      billing: '5d756536e2d9af262cd6da51',
      sourceService: '57a88f8a9ce9da3f72e30fdc'
    }
  ],
  flavour: 'public',
  modifiedOn: '2019-09-08T20:38:38.741Z',
  modifiedBy: 'a.dobrawy@hyperone.com',
  createdBy: 'a.dobrawy@hyperone.com',
  createdOn: '2019-09-08T20:31:50.022Z',
  accessRights: [ '5af0bbbcb7802508ad844caa' ],
  processing: false,
  created: true,
  queue: [
    {
      _id: '5d756536d39c328440cecd8f',
      name: 'create',
      createdBy: 'a.dobrawy@hyperone.com',
      queued: '2019-09-08T20:31:50.026Z',
      state: 'finished',
      resource: { id: '5d756536d39c328440cecd8e', type: 'netadp' }
    },
    {
      _id: '5d7566ced39c328440cecd95',
      name: 'delete',
      createdBy: 'a.dobrawy@hyperone.com',
      queued: '2019-09-08T20:38:38.741Z',
      state: 'finished',
      resource: { id: '5d756536d39c328440cecd8e', type: 'netadp' }
    }
  ],
  state: 'Delete',
  tag: {},
  billingTenant: '5af0bbbcb7802508ad844caa',
  project: '5af0bbbcb7802508ad844caa',
  fqdn: '5d756536d39c328440cecd8e.netadp.pl-waw-1.hyperone.cloud',
  memory: null
}
```

**Comment by gregorybrzeski** [comment]
We should add test for creation of new NIC and deletion of NIC on VM.

I'm also wondering how we can check for further such inconsistencies on API. Something to talk about.

**Comment by ad-m** [comment]
@gregorybrzeski , We have tests for new NIC and deletion of NIC on VM. It does not verify, however, whether we are able to display the answer correctly (render JMESPath transformation as table), because the tests are based on answers similar to the output from `` -o json''. That operation - as show above - works when ```-o json``` used.
 
I added tests in #414 to detect inconsistencies in API on create / show.

**Comment by fredericosilva** [comment]
@ad-m fixed on the API side
