### ISSUE TITLE
Crash on id & uri output

### ISSUE THREAD

**Issue by gregorybrzeski** [hyperonecom/h1-cli#529]
```
$ h1 iam project list -o id
TypeError: Cannot read property 'length' of undefined
    at Lexer.tokenize (webpack:////home/runner/work/h1-cli/h1-cli/node_modules/jmespath/jmespath.js?:233:41)
    at Parser._loadTokens (webpack:////home/runner/work/h1-cli/h1-cli/node_modules/jmespath/jmespath.js?:511:30)
    at Parser.parse (webpack:////home/runner/work/h1-cli/h1-cli/node_modules/jmespath/jmespath.js?:496:16)
    at Object.search (webpack:////home/runner/work/h1-cli/h1-cli/node_modules/jmespath/jmespath.js?:1659:25)
    at queryFilter (webpack:///../cli-core/plugin/formatOutput.js?:12:62)
    at id (webpack:///../cli-core/plugin/formatOutput.js?:49:28)
    at Object.opts.format (webpack:///../cli-core/plugin/formatOutput.js?:78:20)
    at Command.handler (webpack:////home/runner/work/h1-cli/h1-cli/extensions/cli-ext-root-openapi-generator/index.js?:90:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```
$ h1 iam project list -o uri
TypeError: Cannot read property 'length' of undefined
    at Lexer.tokenize (webpack:////home/runner/work/h1-cli/h1-cli/node_modules/jmespath/jmespath.js?:233:41)
    at Parser._loadTokens (webpack:////home/runner/work/h1-cli/h1-cli/node_modules/jmespath/jmespath.js?:511:30)
    at Parser.parse (webpack:////home/runner/work/h1-cli/h1-cli/node_modules/jmespath/jmespath.js?:496:16)
    at Object.search (webpack:////home/runner/work/h1-cli/h1-cli/node_modules/jmespath/jmespath.js?:1659:25)
    at queryFilter (webpack:///../cli-core/plugin/formatOutput.js?:12:62)
    at uri (webpack:///../cli-core/plugin/formatOutput.js?:50:29)
    at Object.opts.format (webpack:///../cli-core/plugin/formatOutput.js?:78:20)
    at Command.handler (webpack:////home/runner/work/h1-cli/h1-cli/extensions/cli-ext-root-openapi-generator/index.js?:90:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Version used: nightly build: `h1-macos.ae920073.tar.gz`

```
$ shasum /usr/local/bin/h1 
c890eef327dfe9a35c38314b3b9bbd52fd7a3341  /usr/local/bin/h1
```

**Comment by ad-m** [comment]
```
$ h3 iam project list -o id
5af0bbbcb7802508ad844caa
5f64e2468c71177993874510
5fb7ac76e7302e032d5b3c25
```
