### ISSUE TITLE
Unable to create network due "socket hang up"

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/h1-cli#75]
```
$ h1 network create --name network-vm-test-1529895223939
error: Uncaught error: socket hang up
error: Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at TLSSocket.socketOnEnd (_http_client.js:416:23)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Occurs multiple times on that commands, so somethings hangs.

**Comment by ad-m** [comment]
```
$ h1 dns zone create --name 1529916483355.a.example.com
error: Uncaught error: socket hang up
error: Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at TLSSocket.socketOnEnd (_http_client.js:416:23)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I do not have any problems with access to the Internet. Problems occur for specific commands. It these same time I can execute others commands & pass tests. 

The previous example is still failing.

@gregorybrzeski , do you can verify that on server-side? How often does this happen? What is the impact on customers?

**Comment by ad-m** [comment]
At night for full tests I got 3 hangs up for following commands:
```
h1 dns zone create --name 1530050017574.a.example.com 
h1 network create --name network-vm-test-1530050018857
h1 disk delete --disk disk-vm-test-vm-dvd-cycle-1530050018857  --yes
```

I records video which demonstrate in these same time:

- curl for API.hyperone.com in loop,
- ```h1 vm list; h1 dns zone list;``` in loop,
- ``` h1 dns zone create --name 1530050017574.a.example.com``` by hand.

Here is video: https://files.jawne.info.pl/private_html/2018_06_phaiz8iekaciegh8meedohqueicoequeiraepu9Uadoo6ooGhe

I have to analyze it via tcpdump, but I am open to any ideas about reason of connection issues. My IP address is 89.64.26.186. My network provider is UPC.

**Comment by gregorybrzeski** [comment]
UPC had some network maintenance approx at 4-5am last night, check if that was during that time.

**Comment by ad-m** [comment]
It also occurred this morning.

**Comment by gregorybrzeski** [comment]
That's interesting then, let's have a look at it collectively once all in the room.

**Comment by ad-m** [comment]
How to access to monitoring node in UPC network?

**Comment by ad-m** [comment]
There was no problem throughout the day on WDC Wi-Fi. Tonight, after switching to the UPC link, I noticed problems again.

**Comment by ad-m** [comment]
```
  Rejected promise returned by test. Reason:

  {
    cmd: {
      cmd: 'dns record-set cname add-record --name cname-1530222017233 --zone 1530222017233.cname.example.com. --value \'cname2.example.com.\'',
      history: [],
    },
    err: Error {
      code: 'ECONNRESET',
      handler: Function handleAddRecord {},
      node: Command {
        config: Object { … },
        description: 'Add record',
        epilog: `Examples␊
        ␊
        Add DNS record␊
        ␊
            $ h1 dns record-set a add-record --zone-name 'my-domain.tld' --name subdomain --value 127.0.0.2␊
        ␊
        `,
        examples: `# Add DNS record␊
        ␊
        ```bash␊
        $ h1 dns record-set a add-record --zone-name 'my-domain.tld' --name subdomain --value 127.0.0.2␊
        ```␊
        `,
        handler: Function handleAddRecord {},
        name: 'add-record',
        optionGroups: Object { … },
        options: Object { … },
        params: {},
        parent: Category { … },
        plugins: Array [ … ],
        plugins$: Promise { … },
        version: undefined,
      },
      parser: ArgumentParser {
        _actionGroups: Array [ … ],
        _actions: Array [ … ],
        _defaults: Object { … },
        _hasNegativeNumberOptionals: [],
        _mutuallyExclusiveGroups: [],
        _optionStringActions: Object { … },
        _optionals: ArgumentGroup { … },
        _positionals: ArgumentGroup { … },
        _regexpNegativeNumber: /^[-]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$/,
        _registries: Object { … },
        _subparsers: null,
        argumentDefault: null,
        conflictHandler: 'error',
        debug: false,
        description: 'Add record',
        epilog: `Examples␊
        ␊
        Add DNS record␊
        ␊
            $ h1 dns record-set a add-record --zone-name 'my-domain.tld' --name subdomain --value 127.0.0.2␊
        ␊
        `,
        formatterClass: Function CustomHelpFormatter { … },
        fromfilePrefixChars: null,
        prefixChars: '-',
        prog: 'h1 dns record-set cname add-record',
        usage: undefined,
        version: undefined,
      },
      response: undefined,
      message: 'socket hang up',
    },
    history: [],
  }

✘-1 ~/Devel/h1-cli [add-tests|✚ 1] 
23:42 $ 
```

**Comment by ad-m** [comment]
No more occurs.
